In [24]:
import pandas as pd
import numpy as np
import yfinance as yf
import requests 
import os
import logging
import time
from tqdm import tqdm

In [ ]:
# Globals

raw_data_dir = "../data/raw"
proc_data_dir = "../data/processed"

# EDIT THIS!!!
headers = {
    "User-Agent": "First Last email@gmail.com"
}

In [7]:
# Setting up logger
logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, filename = "log.log", filemode = "w", 
                    format = "%(asctime)s - %(levelname)s - %(message)s")

## Creating Datasets

In [11]:
# File downloader

def download_file(url: str, filename: str, headers: dict = {}) -> bool:
    save_path = os.path.join(raw_data_dir, filename)

    if os.path.exists(save_path):
        logger.info(f"{filename} already exists. Skipping download.")
        return True
    
    try:
        logger.info(f"Downloading {filename} from web...")

        response = requests.get(url, headers = headers, stream = True)

        response.raise_for_status()

        with open(save_path, 'wb') as file:
            for chunk in response.iter_content(chunk_size=8192):
                file.write(chunk)

        logger.info(f"Successfully saved to {save_path}")
        return True
    
    except Exception as e:
        logger.error(f"Failed to download {filename}: {e}")
        return False

In [14]:
download_file("https://www.sec.gov/files/company_tickers.json","company_tickers.json", headers)

True

In [16]:
df = pd.read_json("../data/raw/company_tickers.json", orient = "index")
df['cik_str'] = df['cik_str'].astype(str).str.zfill(10)

display(df.head())

      cik_str ticker           title
0  0001045810   NVDA     NVIDIA CORP
1  0001652044  GOOGL   Alphabet Inc.
2  0000320193   AAPL      Apple Inc.
3  0000789019   MSFT  MICROSOFT CORP
4  0001018724   AMZN  AMAZON COM INC

In [ ]:
def fetch_single_comp_metrics(ticker: str) -> dict:

    try:
        stock = yf.Ticker(ticker)
        info = stock.info

        return {
            "ticker": ticker,
            
            # Quantitative block for ML
            "forwardPE": info.get("forwardPE"),
            "ev_to_ebitda": info.get("enterpriseToEbitda"),
            "ebitda_margin": info.get("ebitdaMargins"),
            "debt_to_equity": info.get("debtToEquity"),
            
            # Qualitative block for ML
            "sector": info.get("sector", "Unknown"),
            "industry": info.get("industry", "Unknown"),
            "business_summary": info.get("longBusinessSummary", ""),
            
            # Data for valuation
            "ebitda": info.get("ebitda"),
            "total_cash": info.get("totalCash"),
            "total_debt": info.get("totalDebt"),
            "shares_outstanding": info.get("sharesOutstanding")
        }
    except Exception as e:
            logger.warning(f"Failed to fetch data for {ticker}: {e}")
            return None

In [ ]:
# Testing function
fetch_single_comp_metrics("NVDA")

{'ticker': 'NVDA',
 'forwardPE': 17.73965,
 'ev_to_ebitda': 35.888,
 'ebitda_margin': 0.61698,
 'debt_to_equity': 7.255,
 'sector': 'Technology',
 'industry': 'Semiconductors',
 'business_summary': "NVIDIA Corporation operates as a data center scale AI infrastructure company. The company operates through two segments, Compute & Networking, and Graphics segments. The Compute & Networking segment provides data center accelerated computing and networking platforms and artificial intelligence solutions and software, and automotive platforms and autonomous and electric vehicle solutions, including software. The Graphics segment offers GeForce GPUs for gaming and PCs; Quadro/NVIDIA RTX GPUs for enterprise workstation graphics. The company's products are used in gaming, professional visualization, data center, and automotive markets. The company sells its products to original equipment manufacturers, original device manufacturers, system integrators and distributors, independent software vendors, cloud service providers, add-in board manufacturers, distributors, automotive manufacturers and tier-1 automotive suppliers, and other ecosystem participants worldwide. It has a collaboration with Tech Mahindra Limited to develop artificial intelligence powered telco network operations reasoning agent. The company has a strategic partnership with Lumentum Holdings Inc. to develop optics technologies for AI and data centers. It also has a strategic partnership with Nebius Group N.V. to develop and deploy hyperscale cloud for the artificial intelligence market. NVIDIA Corporation was incorporated in 1993 and is headquartered in Santa Clara, California.",
 'ebitda': 133230002176,
 'total_cash': 62556000256,
 'total_debt': 11411999744,
 'shares_outstanding': 24300000000}

In [25]:
def build_csv_comps_table(raw_data_path: str, output_csv: str, chunk_size: int = 50, limit: int = None):
        logger.info("Starting large data pull...")
        df_raw = pd.read_json(raw_data_path, orient='index')
        all_tickers = df_raw['ticker'].tolist()

        if limit:
            all_tickers = all_tickers[:limit]
            logger.info(f"Test Mode: Only processing the first {limit} companies")
        
        # Check if a partial file already exists to resume
        start_index = 0
        if os.path.exists(output_csv):
            existing_df = pd.read_csv(output_csv)
            start_index = len(existing_df)
            logger.info(f"Found existing file. Resuming from ticker {start_index}...")

        for i in range(start_index, len(all_tickers), chunk_size):
            chunk = all_tickers[i : i + chunk_size]
            chunk_data = []
            
            for ticker in tqdm(chunk, desc=f"Chunk {i//chunk_size}", leave=False):
                metrics = fetch_single_comp_metrics(ticker)
                if metrics:
                    chunk_data.append(metrics)
            
            # Save the chunk to the CSV 
            if chunk_data:
                chunk_df = pd.DataFrame(chunk_data)
                # If file exists, append without headers. Otherwise, write new
                chunk_df.to_csv(output_csv, mode='a', header=not os.path.exists(output_csv), index=False)
            
            time.sleep(2) # Safety pause

In [41]:
build_csv_comps_table("../data/raw/company_tickers.json", "../data/raw/company_metrics.csv", 25, 50)

In [ ]:
pd.read_csv("../data/raw/company_metrics.csv")

,ticker,forwardPE,ev_to_ebitda,ebitda_margin,debt_to_ebitda,sector,industry,business_summary,ebitda,total_cash,total_debt,shares_outstanding
0,NVDA,17.739650,35.888,0.61698,0.085656,Technology,Semiconductors,NVIDIA Corporation operates as a data center s...,1.332300e+11,6.255600e+10,1.141200e+10,24300000000
1,GOOGL,25.076876,26.757,0.37279,0.446119,Communication Services,Internet Content & Information,Alphabet Inc. offers various products and plat...,1.501750e+11,1.268430e+11,6.699600e+10,5822000000
2,AAPL,28.615034,25.736,0.35100,0.591941,Technology,Consumer Electronics,"Apple Inc. designs, manufactures, and markets ...",1.529020e+11,6.690700e+10,9.050900e+10,14681140000
3,MSFT,21.752918,16.849,0.57377,0.703405,Technology,Software - Infrastructure,Microsoft Corporation develops and supports so...,1.752590e+11,8.946200e+10,1.232780e+11,7425629076
4,AMZN,26.442839,18.680,0.20327,1.225182,Consumer Cyclical,Internet Retail,"Amazon.com, Inc. engages in the retail sale of...",1.457310e+11,1.230290e+11,1.785470e+11,10754251799
5,AVGO,22.043870,51.863,0.54506,1.774867,Technology,Semiconductors,"Broadcom Inc. designs, develops, and supplies ...",3.721800e+10,1.417400e+10,6.605700e+10,4734668184
6,META,18.855963,16.707,0.50701,0.835012,Communication Services,Internet Content & Information,"Meta Platforms, Inc. engages in the developmen...",1.018920e+11,8.159200e+10,8.508100e+10,2187177748
7,TSLA,141.406310,137.340,0.11076,1.401409,Consumer Cyclical,Auto Manufacturers,"Tesla, Inc. designs, develops, manufactures, l...",1.050300e+10,4.405900e+10,1.471900e+10,3752431984
8,BRK-B,21.795288,-2.125,0.29774,1.224036,Financial Services,Insurance - Diversified,"Berkshire Hathaway Inc., together with its sub...",1.105940e+11,3.733110e+11,1.353710e+11,1390722404
9,WMT,37.981815,24.103,0.06174,1.554147,Consumer Defensive,Discount Stores,Walmart Inc. engages in the operation of retai...,4.402800e+10,1.072700e+10,6.842600e+10,7972402501
10,LLY,21.539768,26.667,0.48625,1.384060,Healthcare,Drug Manufacturers - General,"Eli Lilly and Company discovers, develops, man...",3.169300e+10,7.268000e+09,4.386500e+10,893357420
11,JPM,12.977884,NaN,0.00000,NaN,Financial Services,Banks - Diversified,JPMorgan Chase & Co. operates as a bank and fi...,NaN,1.864181e+12,1.311810e+12,2679500000
12,XOM,14.972042,11.263,0.18334,0.850150,Energy,Oil & Gas Integrated,Exxon Mobil Corporation engages in the explora...,5.938600e+10,1.068100e+10,5.048700e+10,4156559415
13,SPY,NaN,NaN,NaN,NaN,Unknown,Unknown,The trust seeks to achieve its investment obje...,NaN,NaN,NaN,917782016
14,V,21.719925,20.660,0.70032,0.730569,Financial Services,Credit Services,Visa Inc. operates as a payment technology com...,2.898700e+10,1.639700e+10,2.117700e+10,1681093942
15,ASML,32.440170,47.002,0.37549,0.382378,Technology,Semiconductor Equipment & Materials,ASML Holding N.V. provides lithography solutio...,1.226640e+10,1.332210e+10,4.690400e+09,385417665
16,JNJ,18.827188,17.722,0.35392,1.446514,Healthcare,Drug Manufacturers - General,"Johnson & Johnson, together with its subsidiar...",3.410475e+10,2.010200e+10,4.933300e+10,2408613219
17,MU,4.599147,13.877,0.63324,0.293400,Technology,Semiconductors,"Micron Technology, Inc. designs, develops, man...",3.680300e+10,1.458900e+10,1.079800e+10,1127734051
18,MA,22.942862,22.712,0.62651,0.965391,Financial Services,Credit Services,"Mastercard Incorporated, a technology company,...",2.054400e+10,1.089800e+10,1.983300e+10,885216386
19,COST,43.832650,32.317,0.04702,0.759881,Consumer Defensive,Discount Stores,"Costco Wholesale Corporation, together with it...",1.346000e+10,1.112600e+10,1.022800e+10,443652540
20,NFLX,27.737003,33.871,0.30233,1.242741,Communication Services,Entertainment,"Netflix, Inc. provides entertainment services ...",1.365999e+10,9.062359e+09,1.697584e+10,4222162150
21,CYATY,NaN,NaN,0.00000,NaN,Industrials,Electrical Equipment & Parts,"Contemporary Amperex Technology Co., Limited, ...",NaN,NaN,NaN,623661200
22,AMD,23.827635,60.685,0.19472,0.593921,Technology,Semiconductors,"Advanced Micro Devices, Inc. operates as a sem...",6.745000e+09,1.055200e+10,4.006000e+09,1630338779
23,ORCL,21.298878,22.482,0.42826,5.909588,Technology,Software - Infrastructure,Oracle Corporation offers products and service...,2.744100e+10,3.913200e+10,1.621650e+11,2876046000
24,BAC,10.901479,NaN,0.00000,NaN,Financial Services,Banks - Diversified,"Bank of America Corporation, through its subsi...",NaN,7.701630e+11,7.670720e+11,7145709181
25,CVX,16.762075,11.144,0.20379,1.242141,Energy,Oil & Gas Integrated,"Chevron Corporation, through its subsidiaries,...",3.763100e+10,6.297000e+09,4.674300e+10,1991898801
26,CAT,27.685015,28.958,0.20656,3.155791,Industrials,Farm & Heavy Construction Machinery,Caterpillar Inc. provides construction and min...,1.396100e+10,9.333000e+09,4.405800e+10,465287332
27,ABBV,12.951890,14.868,0.47832,2.338142,Healthcare,Drug Manufacturers - General,"AbbVie Inc., a research-based biopharmaceutica...",2.925400e+10,5.257000e+09,6.840000e+10,1768762377
28,PG,19.743330,14.540,0.29047,1.479467,Consumer Defensive,Household & Personal Products,The Procter & Gamble Company provides branded ...,2.476500e+10,1.082500e+10,3.663900e+10,2324000685
29,HD,20.787102,16.076,0.15187,2.635201,Consumer Cyclical,Home Improvement Retail,"The Home Depot, Inc. operates as a home improv...",2.501100e+10,1.389000e+09,6.590900e+10,996027658
30,KO,21.809072,22.273,0.33537,2.980097,Consumer Defensive,Beverages - Non-Alcoholic,"The Coca-Cola Company, a beverage company, man...",1.607800e+10,1.580600e+10,4.791400e+10,4304152877
31,LRCX,37.161716,46.092,0.35717,0.610571,Technology,Semiconductor Equipment & Materials,"Lam Research Corporation designs, manufactures...",7.343529e+09,6.180440e+09,4.483748e+09,1248771000
32,GE,36.439293,31.677,0.23341,2.014108,Industrials,Aerospace & Defense,"General Electric Company, doing business as GE...",1.070300e+10,1.199200e+10,2.155700e+10,1044829602
33,CSCO,18.245499,20.934,0.27587,1.948315,Technology,Communication Equipment,"Cisco Systems, Inc. designs, develops, and sel...",1.629100e+10,1.577700e+10,3.174000e+10,3949893042
34,AMAT,28.147799,35.051,0.31506,0.808865,Technology,Semiconductor Equipment & Materials,"Applied Materials, Inc. provides materials eng...",8.889000e+09,8.511000e+09,7.190000e+09,793609867
35,AZN,25.318956,17.687,0.32823,1.540612,Healthcare,Drug Manufacturers - General,"AstraZeneca PLC, a biopharmaceutical company, ...",1.928000e+10,5.719000e+09,2.970300e+10,1550283527
36,INTC,62.332630,26.953,0.23902,3.729043,Technology,Semiconductors,"Intel Corporation designs, develops, manufactu...",1.263300e+10,3.741600e+10,4.710900e+10,5021010228
37,HSBC,9.366202,NaN,0.00000,NaN,Financial Services,Banks - Diversified,HSBC Holdings plc engages in the provision of ...,NaN,1.161117e+12,6.999060e+11,3429638404
38,PLTR,76.322960,220.603,0.32179,0.159245,Technology,Software - Infrastructure,Palantir Technologies Inc. builds and deploys ...,1.440160e+09,7.177043e+09,2.293380e+08,2291470751
39,BABA,17.746376,17.954,0.13638,2.066414,Consumer Cyclical,Internet Retail,"Alibaba Group Holding Limited, through its sub...",1.386600e+11,3.381100e+11,2.865290e+11,2391756405
40,MRK,12.089643,11.253,0.44769,1.736265,Healthcare,Drug Manufacturers - General,"Merck & Co., Inc. operates as a healthcare com...",2.910500e+10,1.456500e+10,5.053400e+10,2469879206
41,NVS,15.542554,13.506,0.41418,1.510544,Healthcare,Drug Manufacturers - General,"Novartis AG researches, develops, manufactures...",2.347300e+10,1.153300e+10,3.545700e+10,1908151679
42,MS,15.448666,NaN,0.00000,NaN,Financial Services,Capital Markets,"Morgan Stanley, a financial holding company, p...",NaN,6.003910e+11,5.134080e+11,1581386814
43,UNH,15.595979,16.071,0.04832,3.838335,Healthcare,Healthcare Plans,UnitedHealth Group Incorporated operates as a ...,2.162500e+10,2.812100e+10,8.300400e+10,907675839
44,TM,13.509505,4.727,0.12299,6.789375,Consumer Cyclical,Auto Manufacturers,"Toyota Motor Corporation designs, manufactures...",6.204942e+12,1.659209e+13,4.212768e+13,1303393197
45,RTX,26.342905,20.408,0.16630,2.711639,Industrials,Aerospace & Defense,"RTX Corporation, an aerospace and defense comp...",1.473500e+10,7.435000e+09,3.995600e+10,1345974220
46,GS,13.776785,NaN,0.00000,NaN,Financial Services,Capital Markets,"The Goldman Sachs Group, Inc., a financial ins...",NaN,9.966290e+11,7.475830e+11,294993942
47,GEV,43.069470,86.515,0.07868,0.399332,Industrials,Specialty Industrial Machinery,"GE Vernova Inc., an energy company, engages in...",2.995000e+09,8.935000e+09,1.196000e+09,268856205
48,WFC,10.118731,NaN,0.00000,NaN,Financial Services,Banks - Diversified,"Wells Fargo & Company, a financial services co...",NaN,6.120940e+11,4.505940e+11,3064300000
49,SHEL,10.551858,11.827,0.17857,1.588149,Energy,Oil & Gas Integrated,Shell plc operates as an energy and petrochemi...,4.765800e+10,3.021600e+10,7.568800e+10,2798335416

In [39]:
print(yf.Ticker("AEM").info.get("debtToEquity"))

1.299